---
 - name: cleanup deployment on target hosts
   shell : "cd {{ TR_REPO_DIR }} && ./destroy.sh | tee /tmp/destroy.log"
   args:
       executable: /bin/bash
   register: cleanup_result
 - debug:
       msg: "{{ cleanup_result.stdout }}"  

 - name: deleting deployment directory on target hosts
   file: 
       path: "{{ TR_REPO_DIR }}"
       state: absent
   register: delete_dir
   when: "'failed' not in cleanup_result.stdout"
 - debug:   
       msg: "Deployment cleanup has been done"
   when: delete_dir.changed
